Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SIPYME.Logic;
using SIPYME.Models;
using SIPYME.Permisos;

namespace SIPYME.Controllers
{
    [PermisosRol(1)]
    public class AdministradorController : Controller
    {
        public ActionResult Iframe()
        {

            return View("Iframe", lalista());
        }

        public ActionResult ViewAdmin()
        {
            return View();
        }
        //metodos pymes
        public ActionResult ListarPymesAdministrador()
        {
            return View("ListarPymesAdministrador", lalista());
        }
        private List<SelectListItem> lalista()
        {


            List<AreaTrabajo> Lista = Service.Service.listaAreaTrabajos();
            List<SelectListItem> lst = new List<SelectListItem>();
            lst.Add(new SelectListItem
            {
                Value = "",
                Text = "Seleccionar  Area de Trabajo  de la Pyme",
            });

            foreach (AreaTrabajo d in Lista)
            {
                lst.Add(new SelectListItem
                {
                    Value = d.Nombre_area,
                    Text = d.Nombre_area
                });
            }

            ViewBag.ComboBoxData = lst;

            return lst;
        }
        [HttpPost]
        public JsonResult EliminarFotoProducto(Foto objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            resultado = Service.Service.elimnaFotoProducto(objeto.ID);

            return Json(new { resultado = resultado }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult EliminarFotoPyme(Foto objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            resultado = Service.Service.elimnaFotoPyme(objeto.ID);

            return Json(new { resultado = resultado }, JsonRequestBehavior.AllowGet);

        }


        [HttpGet]
        public JsonResult MostrarTodasLasPymes()
        {
            //PARA mostrar pymes
            List<PymeModel> pLista = new List<PymeModel>();
            List<Pyme> pymes = Service.Service.ListaTodasLasPymes();

            foreach (Pyme pyme in pymes)
            {
                PymeModel unitmodelo = new PymeModel();
                unitmodelo.pyme = pyme;
                unitmodelo.fotosProducto = Service.Service.listaFotosProductoPorPyme(pyme.Id);
                unitmodelo.fotosPyme = Service.Service.listaFotosPymePorPyme(pyme.Id);
                pLista.Add(unitmodelo);
            }

            return Json(new { data = pLista }, JsonRequestBehavior.AllowGet);
            ////
        }


        [HttpPost]
        public JsonResult PlataformistaRazonRechazo(Estado_pyme objeto)
        {
            object resultado2;
            int Resultado = 0;
            string mensaje = string.Empty;

            resultado2 = Service.Service.PlataformistaRazonRechazo(objeto, out mensaje, out Resultado);
            return Json(new { resultado = resultado2, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult EditaPyme(Pyme objeto, HttpPostedFileBase upload, HttpPostedFileBase[] producto, HttpPostedFileBase[] pyme)
        {
            object resultado;
            string mensaje = string.Empty;

            List<Foto> fotospyme = new List<Foto>();

            List<Foto> fotosproducto = new List<Foto>();

            objeto.Estado_pyme = "Pendiente";

            if (upload != null && upload.ContentLength > 0)
            {
                byte[] imagenData = null;
                using (var imagen = new BinaryReader(upload.InputStream))
                {
                    imagenData = imagen.ReadBytes(upload.ContentLength);
                }
                objeto.Logo = imagenData;
            }

            try
            {
                if (producto != null && producto.Length > 0)
                {


                    foreach (var archivo in producto)
                    {
                        if (archivo != null && archivo.ContentLength > 0)
                        {
                            byte[] imagenData = null;
                            using (var imagen = new BinaryReader(archivo.InputStream))
                            {
                                imagenData = imagen.ReadBytes(archivo.ContentLength);
                            }

                            Foto fotos = new Foto();
                            fotos.CantidadByte = imagenData;
                            fotos.PymeId = objeto.Id;

                            fotosproducto.Add(fotos);
                        }
                    }

                    // Ahora puedes asignar la lista "fotosproducto" a tu objeto o hacer cualquier otra operación necesaria
                }

                if (fotosproducto.Count != 0)
                    Service.Service.registrarFotosProducto(fotosproducto);


            }
            catch (Exception e)
            {

            }
            try
            {
                if (pyme != null && pyme.Length > 0)
                {


                    foreach (var archivo in pyme)
                    {
                        if (archivo != null && archivo.ContentLength > 0)
                        {
                            byte[] imagenData = null;
                            using (var imagen = new BinaryReader(archivo.InputStream))
                            {
                                imagenData = imagen.ReadBytes(archivo.ContentLength);
                            }

                            Foto fotos = new Foto();
                            fotos.CantidadByte = imagenData;
                            fotos.PymeId = objeto.Id;
                            fotospyme.Add(fotos);
                        }
                    }

                    // Ahora puedes asignar la lista "fotosproducto" a tu objeto o hacer cualquier otra operación necesaria
                }
                if (fotospyme.Count != 0)
                    Service.Service.registrarFotosPyme(fotospyme);


            }
            catch (Exception e)
            {

            }


            resultado = Service.Service.usuarioEditaPyme(objeto, out mensaje);





            ViewData["Mensaje"] = mensaje;
            return View("ListarPymesAdministrador", lalista());



        }
        //private int registrarPyme(Pyme objeto) { 


        //}

        [HttpPost]
        public ActionResult RegistraPyme(Pyme objeto, HttpPostedFileBase upload, HttpPostedFileBase[] producto, HttpPostedFileBase[] pyme)
        {
            List<Foto> fotospyme = new List<Foto>();
            string mensaje = string.Empty;
            List<Foto> fotosproducto = new List<Foto>();
            try
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    byte[] imagenData = null;
                    using (var imagen = new BinaryReader(upload.InputStream))
                    {
                        imagenData = imagen.ReadBytes(upload.ContentLength);
                    }
                    objeto.Logo = imagenData;
                }



            }
            catch (Exception e)
            {
                mensaje = "No se pudo registrar la pyme";
                return Json(new { mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }


            objeto.Estado_pyme = "Pendiente";
            int id = Service.Service.MantenimientoIngresaPyme(objeto, out mensaje);
            if (id == 0)
            {
                ViewData["Mensaje"] = mensaje;
                return View("ListarPymesAdministrador", lalista());
            }




            try
            {
                if (producto != null && producto.Length > 0)
                {


                    foreach (var archivo in producto)
                    {
                        if (archivo != null && archivo.ContentLength > 0)
                        {
                            byte[] imagenData = null;
                            using (var imagen = new BinaryReader(archivo.InputStream))
                            {
                                imagenData = imagen.ReadBytes(archivo.ContentLength);
                            }

                            Foto fotos = new Foto();
                            fotos.CantidadByte = imagenData;
                            fotos.PymeId = id;

                            fotosproducto.Add(fotos);
                        }
                    }

                    // Ahora puedes asignar la lista "fotosproducto" a tu objeto o hacer cualquier otra operación necesaria
                }

                if (fotosproducto.Count != 0)
                    Service.Service.registrarFotosProducto(fotosproducto);


            }
            catch (Exception e)
            {

            }
            try
            {
                if (pyme != null && pyme.Length > 0)
                {


                    foreach (var archivo in pyme)
                    {
                        if (archivo != null && archivo.ContentLength > 0)
                        {
                            byte[] imagenData = null;
                            using (var imagen = new BinaryReader(archivo.InputStream))
                            {
                                imagenData = imagen.ReadBytes(archivo.ContentLength);
                            }

                            Foto fotos = new Foto();
                            fotos.CantidadByte = imagenData;
                            fotos.PymeId = id;
                            fotospyme.Add(fotos);
                        }
                    }

                    // Ahora puedes asignar la lista "fotosproducto" a tu objeto o hacer cualquier otra operación necesaria
                }
                if (fotospyme.Count != 0)

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/Admin")


</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <form class="d-none d-md-inline-block form-inline ms-5 me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <img src="~/imagenes/sipymelogo.jpg" style="width: 180px; height: auto;">
            </div>
        </form>
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <a class="navbar-brand ps-3" href="@Url.Action("IframeLimpio", "Home")">Visualizar Mapa</a>
                <a class="navbar-brand ps-3" href="@Url.Action("Index", "Home")">Iniciar Sesion</a>
            </div>
        </form>


    </nav>
   
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Municipalidad San Pablo Heredia</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/AdminScript")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/Admin")

  
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <form class="d-none d-md-inline-block form-inline me-auto me-md-3 my-2 my-md-0" style="margin-left: 4px;margin-top: 6px;">
            <div class="input-group" style="margin-left: 4px; margin-top: 6px;">
                <img src="~/imagenes/sipymelogo.jpg" style="width: 170px; height: auto;">
            </div>
        </form>

        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group" style="margin-top:5px">
                <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="@Url.Action("Logout","Home")">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </form>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div style="margin-top: 25px; text-align: match-parent;">
                            <a class="navbar-brand ps-3" href="@Url.Action("ViewAdmin","Administrador")">Usuario Administrador</a>
                        </div>
                        <div style="margin-top:20px">
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Mantenimiento
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">

                                    <a class="nav-link" href="@Url.Action("Listausuarios","Administrador")">Mantenimiento de Usuarios</a>
                                    <a class="nav-link" href="@Url.Action("ListarPymesAdministrador","Administrador")">Mantenimiento de Pymes</a>
                                    <a class="nav-link" href="@Url.Action("Bitacora","Administrador")">Bitácora de cambios</a>
                                    <a class="nav-link" href="@Url.Action("Iframe","Administrador")">Visualizar Mapa</a>

                                </nav>
                            </div>

                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logueado como:</div>
                    Usuario Administrador
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Municipalidad San Pablo Heredia</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/AdminScript")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutIframeLimpio.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SIPYME</title>
    
    @Styles.Render("~/Content/Admin")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img src="~/Imagenes/logoMuniBlanco.jpg" alt="Sistema de Patentes San Pablo" style="width: 300px; height: auto;"

            </div>


        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr class="d-none d-xxl-block">
        <footer class=" d-none d-xxl-block">
            <p>&copy; @DateTime.Now.Year - Municipalidad de San Pablo de Heredia</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/AdminScript")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPlataformista.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/Admin")


</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <form class="d-none d-md-inline-block form-inline me-auto me-md-3 my-2 my-md-0" style="margin-left: 4px;margin-top: 6px;">
            <div class="input-group" style="margin-left: 4px; margin-top: 6px;">
                <img src="~/imagenes/sipymelogo.jpg" style="width: 170px; height: auto;">
            </div>
        </form>

        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group" style="margin-top:5px">
                <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="@Url.Action("Logout","Home")">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </form>

    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div style="margin-top: 25px; text-align: match-parent;">
                            <a class="navbar-brand ps-3" href="@Url.Action("ViewPlataformista","Plataformista")">Usuario Plataformista</a>
                        </div>
                        <div style="margin-top:20px">

                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Mantenimiento
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">

                                    <a class="nav-link" href="@Url.Action("ListarPymesPlataformista","Plataformista")">Mantenimiento de Pymes</a>

                                </nav>
                            </div>

                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                    </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logueado como:</div>
                    Usuario Plataformista
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Municipalidad San Pablo Heredia</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/AdminScript")
    @RenderSection("scripts", required: false)
</body>
</html>